# frozen_string_literal: true

class MarketingPagesController < ApplicationController
  before_action :set_showcase, only: %i[homepage alternative]

  PRIMARY_SHOWCASED_PAGE_SLUGS = %w[
    emma-lawler
    kumar
    lindsaycrouse

    ivanachen
    aaron-cohn
    victoria-martinez-de-la-cruz
  ].freeze

  SECONDARY_SHOWCASED_PAGE_SLUGS = %w[
    kaley-wendorf
    mairin
    lily-wang

    david-hagan
    joedaft
    jj
  ].freeze

  TERTIARY_SHOWCASED_PAGE_SLUGS = %w[
    jopie
    matt-mayo
    sinan-ozdemir

    kkurian
    jhm
    jackohara
  ].freeze

  def homepage
    @email_address = EmailAddress.new
    if Rails.configuration.solo_mode
      return redirect_to new_account_registration_path if Account.count.zero?

      @account = Account.first
      return render 'public_pages/show'
    end

    redirect_to page_path(current_account.slug) if current_account
  end

  ALTERNATIVES = {
    'revue' => {
      title: 'Revue',
      description: 'Postcard is a Revue alternative built for dependability. It is a personal website and newsletter that you can host on your own domain.' # rubocop:disable Layout/LineLength
    }
  }.freeze

  def alternative
    @alternative = ALTERNATIVES[params[:slug]]
    raise ActiveRecord::RecordNotFound unless @alternative

    @page_title = @alternative[:title]
    @page_description = @alternative[:description]
    render "marketing_pages/alternative/#{params[:slug]}"
  end

  def sitemap
    # generated by rake task:
    # bundle exec rake sitemap:refresh:no_ping
    send_file('public/sitemaps/sitemap.xml')
  end

  private

  def set_showcase
    return if action_name == 'homepage' && (Rails.configuration.solo_mode || current_account)

    @featured_account = featured_account
    @primary_showcase_accounts = get_accounts(PRIMARY_SHOWCASED_PAGE_SLUGS)
    @secondary_showcase_accounts = get_accounts(SECONDARY_SHOWCASED_PAGE_SLUGS)
    @tertiary_showcase_accounts = get_accounts(TERTIARY_SHOWCASED_PAGE_SLUGS)
  end

  def get_accounts(slugs)
    count = slugs.count

    return showcase_accounts.order(created_at: :desc).limit(count).to_a unless Rails.env.production?

    showcase_accounts.where(slug: slugs).to_a.sort_by do |account|
      slugs.index(account.slug)
    end
  end

  def showcase_accounts
    Account.where(locked_at: nil).with_rich_text_description.includes(:domains, photo_attachment: :blob, cover_attachment: :blob)
  end

  def featured_account
    showcase_accounts.includes(pinned_post: :rich_text_body).find_by(slug: 'philipithomas')
  end
end
